import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test('direct application entry needs no catalog search and persists after refresh', async ({ page, request }, info) => {
  const name = '直录验收公司-' + info.project.name + '-' + Date.now()
  const dialog = page.getByRole('dialog', { name: '新增投递档案' })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const catalogSearches: string[] = []
  page.on('request', req => {
    if (/\/api\/v1\/(companies|positions)\?.*size=30/.test(req.url())) catalogSearches.push(req.url())
  })
  await page.goto('/')
  await page.getByRole('button', { name: '＋ 新增投递', exact: true }).click()
  await expect(dialog.getByRole('button', { name: '直接录入', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(dialog.getByRole('combobox', { name: /投递岗位/ })).toHaveCount(0)
  const types = dialog.getByRole('group', { name: '企业类型', exact: true })
  await expect(types.getByRole('button', { name: '其他', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(types.getByRole('button')).toHaveCount(6)
  await types.getByRole('button', { name: '央国企', exact: true }).click()
  await expect(types.locator('button[aria-pressed="true"]')).toHaveCount(1)
  await expect(types.getByRole('button', { name: '央国企', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await dialog.getByLabel('公司名称', { exact: true }).fill(name)
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('请填写岗位名称', { exact: true })).toBeVisible()
  await dialog.getByLabel('岗位名称', { exact: true }).fill('Java 后端')
  await dialog.getByLabel('备注', { exact: true }).fill('无需提前建立公司和岗位')
  await expect(dialog.getByLabel('公司名称', { exact: true })).toHaveValue(name)
  await dialog.getByLabel('岗位名称', { exact: true }).blur()
  await expect(dialog.getByText('请填写岗位名称', { exact: true })).not.toBeVisible()
  await dialog.getByRole('heading', { name: '新增投递档案' }).scrollIntoViewIfNeeded()
  await mkdir('../target/visual-review', { recursive: true })
  await page.screenshot({ path: '../target/visual-review/entry-' + info.project.name + '.png', animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(catalogSearches).toEqual([])
  await page.reload()
  await page.getByRole('navigation', { name: '工作台导航' }).getByRole('button', { name: '投递台账' }).click()
  await page.getByRole('textbox', { name: '搜索记录' }).fill(name)
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  const row = page.locator('article').filter({ hasText: name })
  await row.getByRole('button', { name: '查看档案 ↗', exact: true }).click()
  await expect(page.locator('.el-drawer').getByText('无需提前建立公司和岗位', { exact: true })).toBeVisible()
  await expect(page.locator('.el-drawer .el-timeline-item')).toHaveCount(1)
  const apps = (await (await request.get('/api/v1/applications', { params: { q: name } })).json()).data
  expect(apps.total).toBe(1)
  const company = (await (await request.get('/api/v1/companies', { params: { q: name } })).json()).data
  expect(company.total).toBe(1)
  expect(company.items[0].type).toBe('STATE_OWNED')
  const positions = (await (await request.get('/api/v1/positions', { params: { q: name } })).json()).data
  expect(positions.total).toBe(1)
  expect(errors).toEqual([])
})

test('existing search offers direct entry and failed or duplicate saves keep input', async ({ page, request }, info) => {
  const name = '切换验收公司-' + info.project.name + '-' + Date.now()
  const dialog = page.getByRole('dialog', { name: '新增投递档案' })
  await page.goto('/')
  await page.getByRole('button', { name: '＋ 新增投递', exact: true }).click()
  await dialog.getByLabel('公司名称', { exact: true }).fill(name)
  await dialog.getByLabel('岗位名称', { exact: true }).fill('Agent 开发')
  await dialog.getByLabel('备注', { exact: true }).fill('切换和失败都保留')
  await dialog.getByRole('group', { name: '企业类型', exact: true }).getByRole('button', { name: '互联网', exact: true }).click()
  await dialog.getByRole('button', { name: '选择已有岗位', exact: true }).click()
  await dialog.getByLabel('投递岗位').fill('无匹配岗位-' + Date.now())
  await expect(page.locator('.position-search-empty')).toContainText('没有匹配岗位')
  await page.getByRole('button', { name: '直接录入公司和岗位', exact: true }).click()
  await expect(dialog.getByLabel('公司名称', { exact: true })).toHaveValue(name)
  await expect(dialog.getByLabel('岗位名称', { exact: true })).toHaveValue('Agent 开发')
  await expect(dialog.getByLabel('备注', { exact: true })).toHaveValue('切换和失败都保留')
  await expect(dialog.getByRole('group', { name: '企业类型', exact: true }).getByRole('button', { name: '互联网', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.route('**/api/v1/applications/quick', route => route.abort())
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('连接失败，请检查本地服务并重试')).toBeVisible()
  await expect(dialog.getByRole('group', { name: '企业类型', exact: true }).getByRole('button', { name: '互联网', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(dialog.getByLabel('公司名称', { exact: true })).toHaveValue(name)
  await expect(dialog.getByLabel('备注', { exact: true })).toHaveValue('切换和失败都保留')
  await page.unroute('**/api/v1/applications/quick')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: '＋ 新增投递', exact: true }).click()
  await dialog.getByLabel('公司名称', { exact: true }).fill(name)
  await dialog.getByLabel('岗位名称', { exact: true }).fill('Agent 开发')
  await dialog.getByLabel('备注', { exact: true }).fill('重复提交的输入')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('该岗位已有投递档案，请打开已有档案')).toBeVisible()
  await expect(dialog.getByLabel('备注', { exact: true })).toHaveValue('重复提交的输入')
  const apps = (await (await request.get('/api/v1/applications', { params: { q: name } })).json()).data
  expect(apps.total).toBe(1)
})

test('ambiguous company can be explicitly selected without losing application details', async ({ page, request }, info) => {
  const name = '同名直录公司-' + info.project.name + '-' + Date.now()
  const companies = []
  for (const type of ['BANK', 'INTERNET']) {
    const result = await request.post('/api/v1/companies', { data: { name, type } })
    expect(result.status()).toBe(201)
    companies.push((await result.json()).data)
  }
  await page.goto('/')
  await page.getByRole('button', { name: '＋ 新增投递', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '新增投递档案' })
  await dialog.getByLabel('公司名称', { exact: true }).fill(name)
  await dialog.getByLabel('岗位名称', { exact: true }).fill('金融科技')
  await dialog.getByLabel('备注', { exact: true }).fill('明确选择银行')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('存在同名公司，请选择已有公司并确认具体公司')).toBeVisible()
  await dialog.getByRole('button', { name: '选择已有公司', exact: true }).click()
  await dialog.getByLabel('所属公司').fill(name)
  await page.getByRole('option', { name: name + ' · 银行 · #' + companies[0].id, exact: true }).click()
  await expect(dialog.getByRole('group', { name: '企业类型', exact: true }).getByRole('button')).toHaveCount(0)
  await expect(dialog.locator('.el-tag').filter({ hasText: '银行' })).toBeVisible()
  await expect(dialog.getByLabel('备注', { exact: true })).toHaveValue('明确选择银行')
  await dialog.locator('summary').click()
  await dialog.getByLabel('工作地点').fill('上海')
  await dialog.getByLabel('岗位方向').fill('金融科技')
  await dialog.getByLabel('招聘批次').fill('2026 秋招')
  await dialog.getByLabel('JD 描述').fill('虚构测试职责')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const apps = (await (await request.get('/api/v1/applications', { params: { q: name } })).json()).data
  expect(apps.total).toBe(1)
  expect(apps.items[0].companyId).toBe(companies[0].id)
  expect(apps.items[0].location).toBe('上海')
  const position = (await (await request.get('/api/v1/positions/' + apps.items[0].jobPositionId)).json()).data
  expect(position.jd).toBe('虚构测试职责')
  const selectedCompany = (await (await request.get('/api/v1/companies/' + companies[0].id)).json()).data
  expect(selectedCompany.type).toBe('BANK')
})
