import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

const envelope = (data: unknown) => ({ code: 'SUCCESS', message: '操作成功', data })
async function openMailbox(page: import('@playwright/test').Page) {
  await page.goto('/')
  await page.getByRole('navigation', { name: '工作台导航' }).getByRole('button', { name: /邮件同步/ }).click()
  await expect(page.getByRole('heading', { name: '连接你的网易邮箱' })).toBeVisible()
}
test('mailbox settings validate, save without exposing code, and survive refresh', async ({ page, request }) => {
  await openMailbox(page)
  await page.getByLabel('邮箱地址', { exact: true }).fill('fixture@163.com')
  await page.getByLabel('客户端授权码', { exact: true }).fill('DemoAuthCode12345')
  await page.getByLabel('首次采集起点').fill('2020-01-01T00:00')
  await page.getByLabel('邮箱类型').selectOption('NETEASE_126')
  await page.getByRole('button', { name: '保存邮箱设置' }).click()
  await expect(page.getByText('邮箱后缀须匹配提供商，文件夹名称不能含控制字符')).toBeVisible()
  await expect(page.getByLabel('客户端授权码')).toHaveValue('DemoAuthCode12345')
  await page.getByLabel('邮箱类型').selectOption('NETEASE_163')
  await page.getByRole('button', { name: '保存邮箱设置' }).click()
  await expect(page.getByText('邮箱设置已保存', { exact: true })).toBeVisible()
  await expect(page.getByLabel('客户端授权码')).toHaveValue('')
  await expect(page.getByRole('button', { name: '测试连接', exact: true })).toBeEnabled()
  const response = await request.get('/api/v1/mailbox')
  expect(response.ok()).toBeTruthy()
  expect(await response.text()).not.toContain('DemoAuthCode12345')
  await openMailbox(page)
  await expect(page.getByLabel('邮箱地址')).toHaveValue('fixture@163.com')
  await expect(page.getByLabel('客户端授权码')).toHaveAttribute('placeholder', '已保存，留空保留原授权码')
})
test('connection and partial sync errors stay actionable without any real mailbox access', async ({ page, request }) => {
  const current = (await (await request.get('/api/v1/mailbox')).json()).data
  const saved = await request.put('/api/v1/mailbox', { data: { email: 'fixture@163.com', provider: 'NETEASE_163', folder: 'INBOX', syncFrom: '2020-01-01T00:00:00Z', authorizationCode: 'DemoAuthCode12345', version: current?.version ?? 0 } })
  expect(saved.ok()).toBeTruthy()
  await page.route('**/api/v1/mailbox/connection-tests', route => route.fulfill({ json: envelope({ status: 'FAILED', imported: 0, scanned: 0, hasMore: false, errorCode: 'AUTHENTICATION', message: '认证失败，请检查授权码及网易邮箱 IMAP 开启状态' }) }))
  await page.route('**/api/v1/mailbox/syncs', route => route.fulfill({ json: envelope({ status: 'PARTIAL', imported: 1, scanned: 1, hasMore: true, errorCode: 'NETWORK', message: '邮箱连接或读取失败，请稍后重试' }) }))
  await openMailbox(page)
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByText('认证失败，请检查授权码及网易邮箱 IMAP 开启状态', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '测试连接', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '立即同步', exact: true }).click()
  await expect(page.getByText('邮箱连接或读取失败，请稍后重试 · 新增 1 封，扫描 1 封')).toBeVisible()
  await expect(page.getByRole('button', { name: '立即同步', exact: true })).toBeEnabled()
})
test('mail search, pagination, bounded text detail and script safety', async ({ page }, info) => {
  const mail = (id: number) => ({ id: String(id), subject: '虚构招聘反馈 ' + id, sender: '虚构 HR <hr@example.invalid>', receivedAt: '2026-10-07T02:00:00Z', sentAt: null, contentStatus: id === 11 ? 'TOO_LARGE' : 'AVAILABLE', bodyTruncated: id === 1 })
  await page.route('**/api/v1/mailbox/messages?*', route => {
    const params = new URL(route.request().url()).searchParams
    const current = Number(params.get('page'))
    const items = params.get('q') ? [mail(1)] : current === 2 ? [mail(11)] : Array.from({ length: 10 }, (_, i) => mail(i + 1))
    return route.fulfill({ json: envelope({ items, total: params.get('q') ? 1 : 11, page: current, size: 10 }) })
  })
  await page.route('**/api/v1/mailbox/messages/*', route => {
    const id = Number(new URL(route.request().url()).pathname.split('/').pop())
    return route.fulfill({ json: envelope({ mail: mail(id), bodyText: id === 11 ? null : "<script>window.__mailExecuted=true</script>\n虚构二面安排 <img src='https://example.invalid/tracker'>" }) })
  })
  const external: string[] = []
  page.on('request', req => { if (req.url().includes('example.invalid')) external.push(req.url()) })
  await openMailbox(page)
  await expect(page.locator('.mail-row')).toHaveCount(10)
  await page.locator('.mail-row').first().click()
  const dialog = page.getByRole('dialog', { name: '采集邮件详情' })
  await expect(dialog.getByText('正文超过 20000 字符，当前显示已截断的文本。')).toBeVisible()
  await expect(dialog.locator('pre')).toContainText('<script>window.__mailExecuted=true</script>')
  expect(await page.evaluate(() => (window as unknown as { __mailExecuted?: boolean }).__mailExecuted)).toBeUndefined()
  await dialog.getByRole('button', { name: /关闭|close/i }).click()
  await page.getByRole('button', { name: '下一页' }).click()
  await expect(page.locator('.mail-row')).toHaveCount(1)
  await page.locator('.mail-row').click()
  await expect(dialog.getByText('邮件超过 2 MiB，只采集了邮件头；请到网易邮箱查看完整内容。')).toBeVisible()
  await dialog.getByRole('button', { name: /关闭|close/i }).click()
  await page.getByRole('textbox', { name: '搜索邮件' }).fill('虚构')
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(page.locator('.mail-row')).toHaveCount(1)
  await expect(page.locator('.mail-row')).toContainText('虚构招聘反馈 1')
  expect(external).toEqual([])
  await mkdir('../target/mailbox-evidence', { recursive: true })
  await page.screenshot({ path: '../target/mailbox-evidence/' + info.project.name + '.png', fullPage: true })
})
