import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test('browser operates persisted catalogs, application and stage history', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const token = info.project.name + '-' + Date.now()
  const company = '星河测试科技-' + token
  const position = 'Java 开发-' + token
  const navigation = page.getByRole('navigation', { name: '工作台导航' })
  const dialog = page.getByRole('dialog', { name: /^(新增|编辑|更新招聘阶段)/ })
  const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '投递台账', exact: true })).toBeVisible()
  await navigation.getByRole('button', { name: '公司库' }).click()
  await page.getByRole('button', { name: '＋ 新增公司', exact: true }).click()
  await dialog.getByLabel('公司名称', { exact: true }).fill(company)
  await dialog.getByLabel('公司官网').fill('javascript:alert(1)')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('请输入有效的 http 或 https 地址')).toBeVisible()
  await dialog.getByLabel('公司官网').fill('https://example.org')
  await noOverflow()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByText(company, { exact: true })).toBeVisible()

  await navigation.getByRole('button', { name: '岗位库' }).click()
  await page.getByRole('button', { name: '＋ 新增岗位', exact: true }).click()
  await dialog.getByLabel('所属公司').click()
  await page.getByRole('option', { name: company, exact: true }).click()
  await dialog.getByLabel('岗位名称', { exact: true }).fill(position)
  await dialog.getByLabel('工作地点').fill('上海')
  await dialog.getByLabel('岗位方向').fill('Java 后端')
  await dialog.getByLabel('招聘批次').fill('2026 秋招')
  await dialog.getByLabel('JD 描述').fill('虚构测试岗位：开发清晰、可维护的 Java 服务。')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const positionRow = page.locator('article').filter({ hasText: position })
  await positionRow.getByRole('button', { name: '建立投递', exact: true }).click()
  await dialog.getByLabel('备注', { exact: true }).fill('浏览器联调记录')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()

  // A failed request leaves the user's unsaved input available for correction.
  await positionRow.getByRole('button', { name: '建立投递', exact: true }).click()
  await dialog.getByLabel('备注', { exact: true }).fill('仍保留的笔记')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('该岗位已有投递档案，请打开已有档案')).toBeVisible()
  await expect(dialog.getByLabel('备注', { exact: true })).toHaveValue('仍保留的笔记')
  await dialog.getByRole('button', { name: '取消', exact: true }).click()

  await navigation.getByRole('button', { name: '投递台账' }).click()
  await page.getByRole('textbox', { name: '搜索记录' }).fill(company)
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  const applicationRow = page.locator('article').filter({ hasText: position })
  await applicationRow.getByRole('button', { name: '查看档案 ↗', exact: true }).click()
  const detail = page.locator('.el-drawer')
  await expect(detail.getByText('浏览器联调记录', { exact: true })).toBeVisible()
  await expect(detail.locator('.el-timeline-item')).toHaveCount(1)
  await detail.getByRole('button', { name: '更新阶段', exact: true }).click()
  await dialog.getByRole('combobox', { name: /招聘阶段/ }).press('ArrowDown')
  await page.getByRole('option', { name: '二面', exact: true }).click()
  await dialog.getByLabel('本次变更备注').fill('直接进入二面，日期待定')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(detail.locator('.el-timeline-item')).toHaveCount(2)
  await expect(detail.getByText('直接进入二面，日期待定')).toBeVisible()
  await noOverflow()
  await detail.getByRole('button', { name: '更新阶段', exact: true }).click()
  await dialog.getByRole('combobox', { name: /招聘阶段/ }).press('ArrowDown')
  await page.getByRole('option', { name: '已结束', exact: true }).click()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.locator('.el-form-item__error').filter({ hasText: '请选择结束原因' })).toBeVisible()
  await dialog.getByRole('combobox', { name: /结束原因/ }).press('ArrowDown')
  await page.getByRole('option', { name: '撤回投递', exact: true }).click()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(detail.locator('.el-timeline-item')).toHaveCount(3)
  await detail.getByRole('button', { name: '编辑投递信息', exact: true }).click()
  await dialog.getByLabel('主要投递渠道').fill('内推')
  await dialog.getByLabel('备注', { exact: true }).fill('已保存的复盘备注')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await expect(page.locator('article').filter({ hasText: position }).getByText('已结束', { exact: true })).toBeVisible()
  await page.locator('article').filter({ hasText: position }).getByRole('button', { name: '查看档案 ↗', exact: true }).click()
  await expect(detail.getByText('已保存的复盘备注', { exact: true })).toBeVisible()
  await expect(detail.locator('.el-timeline-item')).toHaveCount(3)
  await mkdir('../target/browser-evidence', { recursive: true })
  await page.screenshot({ path: '../target/browser-evidence/' + info.project.name + '.png', animations: 'disabled' })
  const bounds = await detail.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(-1)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width + 1)
  await noOverflow()
  expect(errors).toEqual([])
})

test('search empty state and connection failure remain actionable', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索记录' }).fill('no-matching-company-' + Date.now())
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(page.getByRole('heading', { name: '还没有匹配的记录' })).toBeVisible()
  await page.route('**/api/v1/applications?**', route => route.abort())
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect(page.getByText('连接失败，请检查本地服务并重试')).toBeVisible()
  await page.unroute('**/api/v1/applications?**')
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect(page.getByRole('heading', { name: '还没有匹配的记录' })).toBeVisible()
  await page.route('**/api/v1/companies?size=1', route => route.abort())
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect(page.getByText('资料概览加载失败，请点击刷新重试')).toBeVisible()
  await expect(page.getByRole('button', { name: /^目标公司/ })).toContainText('—')
  await page.unroute('**/api/v1/companies?size=1')
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect(page.getByText('资料概览加载失败，请点击刷新重试')).not.toBeVisible()
})

test('conflicting editor preserves input and reloads the latest application', async ({ page, request }) => {
  const name = '并发验收-' + Date.now()
  const company = (await (await request.post('/api/v1/companies', { data: { name, type: 'INTERNET' } })).json()).data
  const position = (await (await request.post('/api/v1/positions', { data: { companyId: company.id, name: '后端岗位' } })).json()).data
  const application = (await (await request.post('/api/v1/applications', { data: { jobPositionId: position.id, stage: 'SUBMITTED' } })).json()).data
  await page.goto('/')
  await page.locator('article').filter({ hasText: name }).getByRole('button', { name: '查看档案 ↗', exact: true }).click()
  await page.getByRole('button', { name: '编辑投递信息', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '编辑投递档案' })
  await dialog.getByLabel('备注', { exact: true }).fill('尚未保存的输入')
  const concurrent = await request.put('/api/v1/applications/' + application.id, { data: { version: 0, notes: '另一个窗口的更新' } })
  expect(concurrent.status()).toBe(200)
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('档案已更新，请刷新后再操作')).toBeVisible()
  await expect(dialog.getByLabel('备注', { exact: true })).toHaveValue('尚未保存的输入')
  await dialog.getByRole('button', { name: '重新加载最新档案' }).click()
  await expect(dialog.getByLabel('备注', { exact: true })).toHaveValue('另一个窗口的更新')
  await dialog.getByLabel('备注', { exact: true }).fill('重新确认后保存')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByText('重新确认后保存', { exact: true })).toBeVisible()
})
