CREATE TABLE mailbox_account (
    id BIGINT PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    provider VARCHAR(24) NOT NULL,
    folder VARCHAR(128) NOT NULL,
    sync_from DATETIME(6) NOT NULL,
    credential VARBINARY(1024) NOT NULL,
    uid_validity BIGINT NULL,
    last_uid BIGINT NULL,
    last_status VARCHAR(16) NOT NULL DEFAULT 'NEVER',
    last_attempt_at DATETIME(6) NULL,
    last_success_at DATETIME(6) NULL,
    last_error VARCHAR(32) NULL,
    last_imported INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT chk_mailbox_singleton CHECK (id = 1),
    CONSTRAINT chk_mailbox_provider CHECK (CAST(provider AS BINARY) IN ('NETEASE_163', 'NETEASE_126', 'NETEASE_YEAH')),
    CONSTRAINT chk_mailbox_status CHECK (CAST(last_status AS BINARY) IN ('NEVER', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED')),
    CONSTRAINT chk_mailbox_progress CHECK ((uid_validity IS NULL AND last_uid IS NULL) OR (uid_validity IS NOT NULL AND last_uid IS NOT NULL AND uid_validity > 0 AND last_uid >= 0)),
    CONSTRAINT chk_mailbox_counts CHECK (version >= 0 AND last_imported >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mail_message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_id BIGINT NOT NULL,
    uid_validity BIGINT NOT NULL,
    uid BIGINT NOT NULL,
    fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    message_id VARCHAR(998) NULL,
    subject VARCHAR(1000) NOT NULL,
    sender VARCHAR(1000) NOT NULL,
    received_at DATETIME(6) NULL,
    sent_at DATETIME(6) NULL,
    body_text MEDIUMTEXT NULL,
    content_status VARCHAR(24) NOT NULL,
    body_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_mail_account FOREIGN KEY (account_id) REFERENCES mailbox_account(id) ON DELETE RESTRICT,
    CONSTRAINT uq_mail_uid UNIQUE (account_id, uid_validity, uid),
    CONSTRAINT uq_mail_fingerprint UNIQUE (account_id, fingerprint),
    CONSTRAINT chk_mail_uid CHECK (uid_validity > 0 AND uid > 0),
    CONSTRAINT chk_mail_content CHECK (CAST(content_status AS BINARY) IN ('AVAILABLE', 'TOO_LARGE')),
    CONSTRAINT chk_mail_truncated CHECK (body_truncated IN (0, 1)),
    INDEX idx_mail_account_id (account_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
